name: Hello CI
run-name: Hello ${{ github.actor }}, this action was triggered by ${{ github.event_name }}
on: [push, pull_request]
jobs:
    hello_job:
        name: hello
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello CI, running on ${{ runner.os }}"
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: list files
              run: |
                ls ${{ github.workspace }}


    plot:
        name: Plot
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

    texlive:
        runs-on: ubuntu-latest
        needs: plot
        container: 
          image: texlive/texlive:latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4    

        - name: Compile LaTeX document
          run: |
            latexmk -pdf main.tex

        - name: Save matplotlib plot as atifact
          uses: actions/upload-artifact@v4
          with:
            name: pdf
            path: main.pdf
            retention-days: 1
            if-no-files-found: error
